

on: 
  workflow_dispatch: 



jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: |
          echo  Hello from ${{ github.job  }}
          sudo  apt search python 
          sudo  apt update 

        
