name: Run first hello welcome to yaml local

on: 
  workflow_dispatch:
    inputs:  
      environment:
       required: true
       type: choice
       options:
          - STG
          - PROD
       default: STG    


jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from first yaml file and env : ${{ inputs.environmet }}"
