name: Run first hello welcome to yaml local

on: 
  repository_dispatch: 
    types:
      - incident_report


jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from first yaml file API Triggerd"
